name: Build and Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build frontend
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > .env
          pnpm install
          pnpm build
          rm -rf node_modules
          tar -czf frontend.tar.gz .next package.json public .env

      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "frontend.tar.gz"
          target: "/home/ubuntu/deploy"

      # - name: Run remote deploy script on EC2
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_KEY }}
      #     port: ${{ secrets.EC2_PORT }}
      #     script: |
      #       cd ~/deploy

      #       tar -xzf frontend.tar.gz -C ~/apps/frontend
      #       tar -xzf backend.tar.gz -C ~/apps/backend

      #       cd ~/apps/frontend
      #       npm ci --omit=dev
      #       pm2 restart frontend

      #       cd ~/apps/backend
      #       npm ci --omit=dev
      #       pm2 restart backend
